#1 Sprint 9
Anastassvirs/java-filmorate pull request #1
Opened 2022-10-21 23:56 UTC by Anastassvirs

2022-10-22 08:10 UTC, Frilock requested changes
Добрый день, оставил пару комментариев к работе. Жду новую версию

2022-10-22 08:10 UTC, Frilock commented on pom.xml
> +	<dependencies>
Съехало форматирование, нужно поправить.

2022-10-22 08:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping(value = "/films")
Смотрите, у Вас над всеми публичными методами стоят аннотации маппинга, где в value указано /films. Чтобы не писать над каждым методом value, можно указать над классом аннотацию RequestMapping, где указать общий префикс для всех методов (общий url)

2022-10-22 08:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (film.getName().equals("")) {
Мне кажется проверки не совсем актуальны. Во первых film может быть null? надо бы проверить. Если нет, то film.getName может быть null и тут у Вас будет NPE, чтобы его не было используйте null safe equals. Objects.equals(o1, o2)
То есть ловить NPE в try-catch как то странно
Так же когда вы проверяете строку, и она может быть как null, так и "", то можно использовать StringUtils.isBlank или isNotBlank

2022-10-22 08:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Лишняя пустая строка

2022-10-22 08:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return null;
А я правильно понимаю, что если валидацию не прошли то будет брошено исключение. Тогда зачем этот блок else, если мы в него никогда не зайдем?

2022-10-22 08:10 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	static UserController userController;
Давайте приватными поля сделаем?

2022-10-22 08:10 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	static void init() {
А зачем статическими делать поля и этот метод? В чем у Вас логика была?

2022-10-22 08:10 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Для улучшения валидации, можно воспользоваться зависимосью
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
В данном случае на поля класса модели можно повесить дополнительные аннотации, например,
@NotNull к полю для проверки на null, @NotBlank — для проверки на пустую строку, @Email — для проверки на соответствие формату электронного адреса.

2022-10-22 22:37 UTC, Anastassvirs commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	static void init() {
Насколько я понимаю, аннотированный @BeforeAll метод должен быть статическим методом в тестовом классе. В таком случае поля тоже должны быть статическими

2022-10-22 23:08 UTC, Anastassvirs commented on pom.xml
> +	<dependencies>
Не уверена, что правильно поняла, что было не так. Не смогла найти проблемы с форматированием

2022-10-23 12:31 UTC, Frilock approved these changes
Принял, по поводу форматирования, там просто блок dependencies и заивиимость dependency на одном уровне, просил это поправить. Но не критично

2022-10-23 13:22 UTC, merged