Sprint 10
Anastassvirs/java-filmorate pull request #2
Opened 2022-11-01 09:06 UTC by Anastassvirs

2022-11-01 18:17 UTC, Frilock requested changes
Добрый день, кажется Вы не до конца со слоями работы приложения разобрались

2022-11-01 18:17 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Вы должны инжектить (внедрять) интерфейс, а не его реализацию, то есть FilmStorage. 
Кроме того, кажется, что вы не до конца разобрались со слоями приложения. 
То есть логика такая: контроллер вызывает методы сервиса, а сервис в свою очередь методы хранилищ.

2022-11-01 18:17 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundAnythingException.java
> +    public NotFoundAnythingException() {
А Вам точно нужен данный конструктор?

2022-11-01 18:17 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void addFriend(Long user1Id, Long user2Id) {
Не очень хорошая практика переменные именовать с использованием числовых идентификаторов. То есть по сути это же идентификатор пользователя и идентификатор друга, по идее userId и friendId

2022-11-01 18:17 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.debug("Друг добавлен. Текущее количество друзей: {}", storage.findById(user1Id).getFriends().size());
Плохая практика делать дополнительный запрос для того чтобы что то залогировать. В данном случае пока БД нет приемлемо, но в целом идея не очень хорошая. Лишняя нагрузка

2022-11-01 18:17 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Long> intersection = new HashSet<Long>(user1Friends);
Если я правильно понимаю, что вы хотите пересечения посчитать. То есть функция Sets.intersection(collection1, collection2)

2022-11-02 14:21 UTC, Frilock requested changes
Не исправлена часть замечаний: 
Вроде Вам писал уже о том, что не нужно инжектить в контроллер сразу хранилище. Нужно в сервисе добавить нужные вам методы, в контроллере использовать сервис, а в сервисе хранилище. Кроме того, правильнее инжектить не конкретную реализацию, а сам интерфейс

2022-11-02 14:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Вроде Вам писал уже о том, что не нужно инжектить в контроллер сразу хранилище. Нужно в сервисе добавить нужные вам методы, в контроллере использовать сервис, а в сервисе хранилище. Кроме того, правильнее инжектить не конкретную реализацию, а сам интерфейс

2022-11-02 14:51 UTC, Anastassvirs commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Я случайно забыла запушить свои коммиты, извините((

2022-11-03 06:59 UTC, Frilock approved these changes
Принято

2022-11-03 06:59 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionFilmorateHandler.java
> +        return new ErrorResponse(
в 1 строку бы влезло...

2022-11-03 06:59 UTC, Frilock commented on pom.xml
> +			<version>31.0.1-jre</version>
Версию потом в properties вынесете

2022-11-03 06:59 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        } else {
Блок else не нужен, то есть у вас в 1м if если вы туда попадете будет исключение брошено, то есть код можно без блока else дальше писать

2022-11-04 12:05 UTC, merged