Add database
Anastassvirs/java-filmorate pull request #3
Opened 2022-11-16 20:01 UTC by Anastassvirs

2022-11-17 16:52 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую итерацию. Будут вопросы пишите

2022-11-17 16:52 UTC, Frilock commented on README.md
> +
Файлы .db должны в gitignore попасть, мне на ревью их видеть нет смысла

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +    public MPA create(@Valid @RequestBody MPA mpa) {
У вас вроде по ТЗ: GendeDbStorage, MpaDbStorage - только getById + getAll. То есть для этих сущностей только такие методы необходимо реализовать

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +    public MPA findMPA(@PathVariable Long mpaId) {
По поводу MPA, кажется что лучше назвать сущность Mpa, и соответственно, поменять другие названия

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
А почему коллекцию Genre не инициализируете?

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private Long film_id;
По Java Code конвенции переменные необходимо именовать с использованием CamelCase, т.е. filmId...

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MPAService.java
> +@Slf4j
Лишняя аннотация, не вижу использования логгера

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    MPAStorage mpaStorage;
А почему тут модификаторы отсутствует?

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Переборщили с кол-вом методов =)

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        mpaStorage = new MPADbStorage(jdbcTemplate);
У Вас же Spring, одним из базовых парадигм которого является внедрение зависимостей и инверсия управления. То есть Ваш MpaStorage является спринговым бином, и Вам его нужно инжектить (внедрять, как вы с другими сервисами поступали), а не создавать через new. Спринговые бины через new не создаются обычно. Нужно переделать конструктор

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> findAll() {
Над другими методами стоит Override, а тут нет

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                .releaseDate(rs.getDate("release_date").toLocalDate())
rs.getDate("release_date") - null не вернет? Иначе вы получите NPE ошибку

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            log.debug("Добавлен " +
лог в одну строчку влезает

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
Вообще бы по хорошему сделать отдельный слой приложения для так называемых мапперов, это бы упростило код. Но тут на Ваше усмотрение

2022-11-17 16:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Long id = (long) -1;
Зачем инициализируете -1? Инициализировать переменные заведомо кривыми данными не очень хорошая практика

2022-11-17 16:52 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
По моему это onConstructor_ = @Autowired по умолчанию используется, и можно просто @RequiredArgsConstructor

2022-11-17 16:52 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +public class FilmorateApplicationTests {
Вы как то тестируете все в 1 классе, это не очень хорошая идея. Тестируйте каждую таблицу (цепочку контроллер/сервис/дао) в отдельном классе, например, MpaControllerTest, FilmControllerTest и т.д.

2022-11-17 18:54 UTC, Anastassvirs commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
у меня не работает без него(

2022-11-17 19:29 UTC, Anastassvirs commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
Я пыталась сделать это, но не нашла хорошего туториала, как лучше это сделать.. К тому же, время жесткого дедлайна поджимало. Я просто не могу до конца понять, какая структура должна быть у этого слоя приложения

2022-11-17 19:31 UTC, Anastassvirs commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Выдает следующую ошибку:
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [final ru.yandex.practicum.filmorate.controller.MpaController mpaController] in constructor [public ru.yandex.practicum.filmorate.MpaControllerTest(ru.yandex.practicum.filmorate.controller.MpaController)].
Другие студенты писали в треде, что у них тоже не работало без этого

2022-11-17 19:58 UTC, Anastassvirs commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +    public MPA findMPA(@PathVariable Long mpaId) {
После того, как я переименовала все сущности с MPA на Mpa, тесты на github выдали огромное количество ошибок, хотя в Postman все тесты проходят. Я погуглила ошибки и выяснилось, что проблема именно в переименовании : "This happens when you have 1 name for the Java class on hard disk and another name of Java class in the code". Не знаю, как можно исправить это при взаимодействии с GitHub, поэтому вынуждена была вернуть все как было

2022-11-18 14:32 UTC, Frilock requested changes
Добрый вечер, на часть комментариев вы мне не ответили и не поправили замечания.

2022-11-18 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private int compare(Film f0, Film f1) {
Вообще лучше в этот метод передавать 2 числа, а запросы делать заранее, а то метод compare какой то сложный выходит. У него задача по идее сравнивать 2 значения, а тут идут запросы какие то...

2022-11-18 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MPAService.java
> +@Slf4j
Лишняя аннотация, так и не удалили

2022-11-18 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    List<Long> findLikesOfFilm(Long filmId) {
Модификатор для метода пропустили

2022-11-18 21:08 UTC, Anastassvirs commented
Может быть, часть комментариев у меня не отображается, потому что этих правок у меня не было в предыдущем ревью

2022-11-19 15:27 UTC, Frilock requested changes
Добрый вечер, опять же не исправлены все комментарии. Пришлю скриншот Вам в Slack

2022-11-20 11:08 UTC, Frilock approved these changes
Добрый день, в общем работу я принял, в целом критических замечаний нет, но посмотрите комментарии. Там есть нюансы, хотелось бы чтобы вы потом их поправили.

2022-11-20 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @GetMapping("/filmgenres/{filmID}")
Вообще бы по хорошему Id в одном формате именовать, я бы предложил Id, вместо ID, просто иначе может потом проблемы разные возникнуть

2022-11-20 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, MPAStorage mpaStorage, GenreStorage genreStorage){
Чтобы большие конструкторы не писать, можно вешать над классом RequiredArgsConstructor и спринг все равно будет инжектить бины, а вы избавитесь от конструктора в явном виде

2022-11-20 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeDbStorage.java
> +        String sqlQuery = "INSERT INTO likes (film_id, user_id) " +
В одну строчку SQLка влезает

2022-11-20 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        rs.getDate("birthday");
Всю данную проверку из 6ти строк можно заменить на - 
LocalDate birthday = rs.getDate("birthday") == null ? null : rs.getDate("birthday").toLocalDate();

2022-11-20 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql1 = "SELECT u.user_id," +
А почему не просто SELECT * ....? вместо перечисления

2022-11-20 21:28 UTC, merged